baseURL: https://kozin.cc/
title: Stanislav Kozin's Webpage
theme: kozin

defaultContentLanguage: en

Params:
  logo: images/header.png
  author:
    name: Stanislav Kozin
    email: stan@kozin.cc

Languages:
  en:
    contentDir: content/eng
    weight: 0
    locale: en-us
    label: 🇺🇸
    title: Stanislav Kozin' Homepage
    menu:
        main:
          - url: /
            name: Home
            weight: 0
          - url: /about/
            name: About
            weight: 1


  ru:
    contentDir: content/rus
    weight: 1
    locale: ru-ru
    label: 🇷🇺
    title: Станислав Козин
    menu:
      main:
        - url: /
          name: Домой
          weight: 0
        - url: /about/
          name: Обо Мне
          weight: 1